#!/bin/bash

# Time-stamp: <2020-08-04 17:54:56 Tuesday by ahei>

home=`dirname "$0"`
home=`cd "$home"; pwd`

"${home}"/lisps/untgz.sh
"${home}"/install.emacs.sh

cd $home/lisps && git submodule update --init --recursive && git pull origin master
